# Generated by Django 3.2.13 on 2023-04-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0008_alter_workschedules_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('useraccess', models.CharField(max_length=255)),
                ('passphrase', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employees')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
