# Generated by Django 3.2.13 on 2023-04-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_users_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserType',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Employees', 'Employees')], default='Employees', max_length=255),
        ),
    ]
