# Generated by Django 3.2.13 on 2023-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_users_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
