# Generated by Django 3.2.13 on 2023-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='employees',
            name='civilstatus',
            field=models.CharField(max_length=255, null=True, verbose_name='Civil Status: '),
        ),
        migrations.AddField(
            model_name='employees',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date: '),
        ),
        migrations.AddField(
            model_name='employees',
            name='firstname',
            field=models.CharField(max_length=255, null=True, verbose_name='First Name: '),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(max_length=255, null=True, verbose_name='Gender: '),
        ),
        migrations.AddField(
            model_name='employees',
            name='lastname',
            field=models.CharField(max_length=255, null=True, verbose_name='Last Name: '),
        ),
        migrations.AddField(
            model_name='employees',
            name='middlename',
            field=models.CharField(max_length=255, null=True, verbose_name='Middle Name: '),
        ),
        migrations.AddField(
            model_name='employees',
            name='suffix',
            field=models.CharField(max_length=255, null=True, verbose_name='Suffix: '),
        ),
        migrations.AddField(
            model_name='employees',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Data: '),
        ),
    ]
