# Generated by Django 3.2.13 on 2023-04-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_auto_20230330_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='EmploymentDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='RegularizationDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='isRegular',
            field=models.BooleanField(default=False),
        ),
    ]
