# Generated by Django 3.2.13 on 2023-05-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_alter_workschedules_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
